#if UNITY_EDITOR
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

/// <summary>
/// Small, safe Editor tools for AI-assisted Unity setup and prototype creation.
/// Scene and prefab changes are generated through Unity APIs instead of hand-editing YAML.
/// </summary>
public static class AiGameProjectTools
{
    private const string MainScenePath = "Assets/Scenes/Main.unity";
    private const int StarCount = 10;

    private static readonly string[] RequiredFolders =
    {
        "Assets/Scripts",
        "Assets/Scripts/Player",
        "Assets/Scripts/Collectibles",
        "Assets/Scripts/Game",
        "Assets/Editor",
        "Assets/Scenes",
        "Assets/Prefabs",
        "Assets/Materials",
        "Assets/Art",
        "Assets/Audio",
        "Assets/Tests/EditMode",
        "Assets/Tests/PlayMode"
    };

    [MenuItem("AI Tools/Validate Project Setup")]
    public static void ValidateProjectSetup()
    {
        var missing = 0;

        foreach (var folder in RequiredFolders)
        {
            if (AssetDatabase.IsValidFolder(folder))
            {
                Debug.Log("[AI Tools] OK folder: " + folder);
            }
            else
            {
                missing++;
                Debug.LogWarning("[AI Tools] Missing folder: " + folder);
            }
        }

        var hasAgents = File.Exists(Path.Combine(Directory.GetCurrentDirectory(), "AGENTS.md"));
        var hasReadme = File.Exists(Path.Combine(Directory.GetCurrentDirectory(), "README.md"));
        var hasGitignore = File.Exists(Path.Combine(Directory.GetCurrentDirectory(), ".gitignore"));

        Debug.Log("[AI Tools] AGENTS.md: " + (hasAgents ? "present" : "missing"));
        Debug.Log("[AI Tools] README.md: " + (hasReadme ? "present" : "missing"));
        Debug.Log("[AI Tools] .gitignore: " + (hasGitignore ? "present" : "missing"));
        Debug.Log("[AI Tools] Project setup validation complete. Missing folders: " + missing);
    }

    [MenuItem("AI Tools/Create Star Collector Prototype")]
    public static void CreateStarCollectorPrototype()
    {
        EnsureFolders();

        var materials = CreatePrototypeMaterials();
        var playerPrefab = CreatePlayerPrefab(materials["Player"]);
        var starPrefab = CreateStarPrefab(materials["Star"]);

        var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);
        scene.name = "Main";

        CreateGround(materials["Ground"]);
        CreateLights();

        var manager = new GameObject("Game Manager").AddComponent<StarCollectorGameManager>();
        var player = (GameObject)PrefabUtility.InstantiatePrefab(playerPrefab);
        player.name = "Player";
        player.transform.position = new Vector3(0f, 1.05f, -5f);

        var camera = CreateCamera(player.transform);
        CreateUi(manager);
        CreateStars(starPrefab, manager);

        Selection.activeGameObject = player;
        EditorSceneManager.SaveScene(scene, MainScenePath);
        WriteProjectReport();

        Debug.Log("[AI Tools] Star Collector prototype created at " + MainScenePath + ". Press Play to test it.");
        Debug.Log("[AI Tools] Player uses WASD or arrow keys. Collect all " + StarCount + " stars to win.");
    }

    [MenuItem("AI Tools/Write Project Report")]
    public static void WriteProjectReport()
    {
        Directory.CreateDirectory("docs");

        var report = new StringBuilder();
        report.AppendLine("# Unity Project Report");
        report.AppendLine();
        report.AppendLine("Generated by `AI Tools > Write Project Report`.");
        report.AppendLine();
        report.AppendLine("## Prototype");
        report.AppendLine();
        report.AppendLine("- Game: Star Collector Adventure / 星星收集小冒险");
        report.AppendLine("- Scene: `Assets/Scenes/Main.unity`");
        report.AppendLine("- Goal: move the capsule player, collect 10 stars, and show the win message.");
        report.AppendLine();
        report.AppendLine("## Main GameObjects");
        report.AppendLine();
        report.AppendLine("- `Player`: capsule with `CharacterController` and `StarCollectorPlayerController`.");
        report.AppendLine("- `Main Camera`: follows the player with `CameraFollow`.");
        report.AppendLine("- `Game Manager`: tracks score and win state with `StarCollectorGameManager`.");
        report.AppendLine("- `Star 01` ... `Star 10`: trigger collectibles with `CollectibleStar`.");
        report.AppendLine("- `Score Text` and `Win Text`: simple UGUI status display.");
        report.AppendLine();
        report.AppendLine("## Scripts");
        report.AppendLine();
        report.AppendLine("- `Assets/Scripts/Player/StarCollectorPlayerController.cs`");
        report.AppendLine("- `Assets/Scripts/Player/CameraFollow.cs`");
        report.AppendLine("- `Assets/Scripts/Collectibles/CollectibleStar.cs`");
        report.AppendLine("- `Assets/Scripts/Game/StarCollectorGameManager.cs`");
        report.AppendLine("- `Assets/Editor/AiGameProjectTools.cs`");
        report.AppendLine();
        report.AppendLine("## Prefabs And Materials");
        report.AppendLine();
        report.AppendLine("- `Assets/Prefabs/Player.prefab`");
        report.AppendLine("- `Assets/Prefabs/CollectibleStar.prefab`");
        report.AppendLine("- `Assets/Materials/PlayerBlue.mat`");
        report.AppendLine("- `Assets/Materials/StarGold.mat`");
        report.AppendLine("- `Assets/Materials/GroundGreen.mat`");
        report.AppendLine();
        report.AppendLine("## How To Play");
        report.AppendLine();
        report.AppendLine("1. In Unity, choose `AI Tools > Create Star Collector Prototype` if the scene has not been generated yet.");
        report.AppendLine("2. Open `Assets/Scenes/Main.unity`.");
        report.AppendLine("3. Press Play.");
        report.AppendLine("4. Move with WASD or arrow keys.");
        report.AppendLine("5. Collect all 10 stars to show `You Win!`.");
        report.AppendLine();
        report.AppendLine("## Known Limits");
        report.AppendLine();
        report.AppendLine("- This is a first playable learning prototype using simple geometry, not final art.");
        report.AppendLine("- Official Unity MCP is still blocked by Unity plan entitlement; community MCP is configured separately.");

        File.WriteAllText("docs/UNITY_PROJECT_REPORT.md", report.ToString());
        AssetDatabase.Refresh();
        Debug.Log("[AI Tools] Wrote docs/UNITY_PROJECT_REPORT.md");
    }

    private static void EnsureFolders()
    {
        foreach (var folder in RequiredFolders)
        {
            EnsureFolder(folder);
        }
    }

    private static void EnsureFolder(string folder)
    {
        if (AssetDatabase.IsValidFolder(folder))
        {
            return;
        }

        var parts = folder.Split('/');
        var current = parts[0];

        for (var i = 1; i < parts.Length; i++)
        {
            var next = current + "/" + parts[i];
            if (!AssetDatabase.IsValidFolder(next))
            {
                AssetDatabase.CreateFolder(current, parts[i]);
            }

            current = next;
        }
    }

    private static Dictionary<string, Material> CreatePrototypeMaterials()
    {
        var materials = new Dictionary<string, Material>
        {
            ["Player"] = CreateOrUpdateMaterial("Assets/Materials/PlayerBlue.mat", new Color(0.2f, 0.45f, 1f)),
            ["Star"] = CreateOrUpdateMaterial("Assets/Materials/StarGold.mat", new Color(1f, 0.82f, 0.18f)),
            ["Ground"] = CreateOrUpdateMaterial("Assets/Materials/GroundGreen.mat", new Color(0.22f, 0.62f, 0.34f))
        };

        AssetDatabase.SaveAssets();
        return materials;
    }

    private static Material CreateOrUpdateMaterial(string path, Color color)
    {
        var material = AssetDatabase.LoadAssetAtPath<Material>(path);
        if (material == null)
        {
            var shader = Shader.Find("Universal Render Pipeline/Lit");
            if (shader == null)
            {
                shader = Shader.Find("Standard");
            }

            material = new Material(shader);
            AssetDatabase.CreateAsset(material, path);
        }

        material.color = color;
        EditorUtility.SetDirty(material);
        return material;
    }

    private static GameObject CreatePlayerPrefab(Material playerMaterial)
    {
        var player = GameObject.CreatePrimitive(PrimitiveType.Capsule);
        player.name = "Player";
        player.tag = "Player";
        player.transform.localScale = new Vector3(1f, 1f, 1f);

        var primitiveCollider = player.GetComponent<CapsuleCollider>();
        if (primitiveCollider != null)
        {
            UnityEngine.Object.DestroyImmediate(primitiveCollider);
        }

        var renderer = player.GetComponent<Renderer>();
        renderer.sharedMaterial = playerMaterial;

        var controller = player.AddComponent<CharacterController>();
        controller.height = 2f;
        controller.radius = 0.45f;
        controller.center = Vector3.zero;

        player.AddComponent<StarCollectorPlayerController>();

        var prefab = SavePrefab(player, "Assets/Prefabs/Player.prefab");
        UnityEngine.Object.DestroyImmediate(player);
        return prefab;
    }

    private static GameObject CreateStarPrefab(Material starMaterial)
    {
        var star = GameObject.CreatePrimitive(PrimitiveType.Sphere);
        star.name = "CollectibleStar";
        star.transform.localScale = new Vector3(0.7f, 0.7f, 0.7f);

        var renderer = star.GetComponent<Renderer>();
        renderer.sharedMaterial = starMaterial;

        var collider = star.GetComponent<SphereCollider>();
        collider.isTrigger = true;
        collider.radius = 0.65f;

        star.AddComponent<CollectibleStar>();

        var prefab = SavePrefab(star, "Assets/Prefabs/CollectibleStar.prefab");
        UnityEngine.Object.DestroyImmediate(star);
        return prefab;
    }

    private static GameObject SavePrefab(GameObject source, string path)
    {
        var prefab = PrefabUtility.SaveAsPrefabAsset(source, path);
        AssetDatabase.SaveAssets();
        return prefab;
    }

    private static void CreateGround(Material groundMaterial)
    {
        var ground = GameObject.CreatePrimitive(PrimitiveType.Cube);
        ground.name = "Ground";
        ground.transform.position = new Vector3(0f, -0.05f, 0f);
        ground.transform.localScale = new Vector3(24f, 0.1f, 24f);
        ground.GetComponent<Renderer>().sharedMaterial = groundMaterial;
    }

    private static void CreateLights()
    {
        var sun = new GameObject("Sun Light");
        var light = sun.AddComponent<Light>();
        light.type = LightType.Directional;
        light.intensity = 1.2f;
        sun.transform.rotation = Quaternion.Euler(50f, -30f, 0f);

        var fill = new GameObject("Soft Fill Light");
        var fillLight = fill.AddComponent<Light>();
        fillLight.type = LightType.Point;
        fillLight.intensity = 2f;
        fillLight.range = 14f;
        fill.transform.position = new Vector3(0f, 5f, -6f);
    }

    private static Camera CreateCamera(Transform player)
    {
        var cameraObject = new GameObject("Main Camera");
        cameraObject.tag = "MainCamera";
        cameraObject.transform.position = new Vector3(0f, 8f, -12f);
        cameraObject.transform.rotation = Quaternion.Euler(45f, 0f, 0f);

        var camera = cameraObject.AddComponent<Camera>();
        camera.clearFlags = CameraClearFlags.Skybox;
        camera.fieldOfView = 55f;

        var follow = cameraObject.AddComponent<CameraFollow>();
        follow.SetTarget(player);
        return camera;
    }

    private static void CreateUi(StarCollectorGameManager manager)
    {
        var canvasObject = new GameObject("Canvas");
        var canvas = canvasObject.AddComponent<Canvas>();
        canvas.renderMode = RenderMode.ScreenSpaceOverlay;
        canvasObject.AddComponent<CanvasScaler>();
        canvasObject.AddComponent<GraphicRaycaster>();

        var scoreText = CreateText(canvasObject.transform, "Score Text", "Score: 0 / " + StarCount, new Vector2(20f, -20f), 30, TextAnchor.UpperLeft);
        var winText = CreateText(canvasObject.transform, "Win Text", "You Win!", Vector2.zero, 56, TextAnchor.MiddleCenter);
        winText.gameObject.SetActive(false);

        manager.Configure(scoreText, winText, StarCount);
    }

    private static Text CreateText(Transform parent, string name, string text, Vector2 anchoredPosition, int fontSize, TextAnchor alignment)
    {
        var textObject = new GameObject(name);
        textObject.transform.SetParent(parent, false);

        var rect = textObject.AddComponent<RectTransform>();
        rect.anchorMin = alignment == TextAnchor.MiddleCenter ? new Vector2(0.5f, 0.5f) : new Vector2(0f, 1f);
        rect.anchorMax = rect.anchorMin;
        rect.pivot = alignment == TextAnchor.MiddleCenter ? new Vector2(0.5f, 0.5f) : new Vector2(0f, 1f);
        rect.anchoredPosition = anchoredPosition;
        rect.sizeDelta = alignment == TextAnchor.MiddleCenter ? new Vector2(420f, 120f) : new Vector2(320f, 60f);

        var uiText = textObject.AddComponent<Text>();
        uiText.text = text;
        uiText.font = GetBuiltinFont();
        uiText.fontSize = fontSize;
        uiText.alignment = alignment;
        uiText.color = Color.white;

        return uiText;
    }

    private static Font GetBuiltinFont()
    {
        var font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
        if (font == null)
        {
            font = Resources.GetBuiltinResource<Font>("Arial.ttf");
        }

        return font;
    }

    private static void CreateStars(GameObject starPrefab, StarCollectorGameManager manager)
    {
        for (var i = 0; i < StarCount; i++)
        {
            var angle = i * Mathf.PI * 2f / StarCount;
            var radius = i % 2 == 0 ? 7f : 4.5f;
            var position = new Vector3(Mathf.Cos(angle) * radius, 0.8f, Mathf.Sin(angle) * radius);

            var star = (GameObject)PrefabUtility.InstantiatePrefab(starPrefab);
            star.name = "Star " + (i + 1).ToString("00");
            star.transform.position = position;

            var collectible = star.GetComponent<CollectibleStar>();
            if (collectible != null)
            {
                collectible.SetGameManager(manager);
            }
        }
    }
}
#endif
